apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: localhost:32000/fastapi-service:latest
          ports:
            - containerPort: 8000
