apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: observability
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    nodePort: 30030