apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fastapi-deployment.yaml
  - fastapi-service.yaml
  - locust-k8s.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-datasources.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
images:
  - name: camidzn/api
    newTag: 20250517-8
  - name: camidzn/locust
    newTag: 20250517-8
