apiVersion: v1
kind: Namespace
metadata:
  name: loadtest

---
# ===== Master Deployment =====
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: <DOCKERHUB_USER>/locust:latest
          args:
            - "-f"
            - "locustfile.py"
            - "--master"
          ports:
            - containerPort: 8089   # UI
            - containerPort: 5557   # RPC (master<->workers)

---
# ===== RPC Service para workers =====
apiVersion: v1
kind: Service
metadata:
  name: locust-master-rpc
  namespace: loadtest
spec:
  type: ClusterIP
  selector:
    app: locust-master
  ports:
    - name: rpc
      port: 5557
      targetPort: 5557

---
# ===== UI Service =====
apiVersion: v1
kind: Service
metadata:
  name: locust-master-ui
  namespace: loadtest
spec:
  type: NodePort
  selector:
    app: locust-master
  ports:
    - name: web
      port: 8089
      targetPort: 8089
      nodePort: 30009

---
# ===== Workers Deployment =====
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: loadtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: <DOCKERHUB_USER>/locust:latest
          args:
            - "-f"
            - "locustfile.py"
            - "--worker"
            - "--master-host"
            - "locust-master-rpc.loadtest.svc.cluster.local"  # servicio RPC
          ports:
            - containerPort: 5558  # comunicación worker->master

---
# ===== Stats Service (opcional) =====
apiVersion: v1
kind: Service
metadata:
  name: locust-master-stats
  namespace: loadtest
spec:
  type: ClusterIP
  selector:
    app: locust-master
  ports:
    - name: stats
      port: 5557
      targetPort: 5557