apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: camidzn/locust:latest
          args:
            - "-f"
            - "locustfile.py"
            - "--master"
          ports:
            - containerPort: 8089
            - containerPort: 5557
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master-ui
  namespace: loadtest
spec:
  type: NodePort
  selector:
    app: locust-master
  ports:
    - name: web
      port: 8089
      targetPort: 8089
      nodePort: 30009
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master-rpc
  namespace: loadtest
spec:
  type: ClusterIP
  selector:
    app: locust-master
  ports:
    - name: rpc
      port: 5557
      targetPort: 5557
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: loadtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: camidzn/locust:latest
          args:
            - "-f"
            - "locustfile.py"
            - "--worker"
            - "--master-host"
            - "locust-master-rpc.loadtest.svc.cluster.local"
          ports:
            - containerPort: 5558
