apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taller-mlops-daniel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CamiDzN/TallerCI_CD
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: loadtest
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
